using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PixelCore.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ComponentTableGenerator : IIncrementalGenerator
{
    private const string ComponentFullName = "PixelCore.Runtime.Core.Component";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var names = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList.Types.Count: > 0 },
                transform: static (ctx, ct) =>
                    Eligible(ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node, ct) as INamedTypeSymbol))
            .Where(static n => n is not null)
            .Select(static (n, _) => n!)
            .Collect();

        context.RegisterSourceOutput(names, static (spc, list) => spc.AddSource("ComponentTable.g.cs", Render(list)));
    }

    internal static string? Eligible(INamedTypeSymbol? t)
    {
        if (t is null || t.TypeKind != TypeKind.Class || t.IsAbstract || t.IsStatic) return null;
        if (t.DeclaredAccessibility != Accessibility.Public) return null;
        if (t.ContainingType is not null) return null;
        if (t.IsGenericType) return null;
        if (!DerivesFromComponent(t)) return null;
        if (!t.InstanceConstructors.Any(c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public))
            return null;
        string ns = t.ContainingNamespace.IsGlobalNamespace ? "" : t.ContainingNamespace.ToDisplayString();
        if (ns.StartsWith("PixelCore.Editor", StringComparison.Ordinal)) return null;
        return ns.Length == 0 ? t.Name : ns + "." + t.Name;
    }

    private static bool DerivesFromComponent(INamedTypeSymbol t)
    {
        for (var b = t.BaseType; b is not null; b = b.BaseType)
            if (b.ToDisplayString() == ComponentFullName) return true;
        return false;
    }

    internal static string Render(ImmutableArray<string> names)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Produced at compile time by the PixelCore source generator (tools/ComponentTableGenerator).\n//   It never lands on disk and cannot go stale.\n");
        sb.Append("//   Component subclasses (public, non-nested, non-generic, default constructor, outside Editor)\n//   are registered as name -> type -> constructor.\n");
        sb.Append("// </auto-generated>\n\n");
        sb.Append("namespace PixelCore.Runtime.Serialization;\n\n");
        sb.Append("public static partial class ComponentTypes\n{\n");
        sb.Append("    static partial void RegisterGenerated()\n    {\n");
        foreach (var n in names.Distinct(StringComparer.Ordinal).OrderBy(n => n, StringComparer.Ordinal))
            sb.Append("        Register(\"").Append(n).Append("\", typeof(global::").Append(n)
              .Append("), static () => new global::").Append(n).Append("());\n");
        sb.Append("    }\n}\n");
        return sb.ToString();
    }
}
